# SPDX-FileCopyrightText: © 2023 Siemens AG
# SPDX-License-Identifier: MIT

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

project_name: dda

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

builds:
  - env:
      - CGO_ENABLED=0
    # To include VCS information into binaries, the current directory must be the main package.
    dir: cmd/dda
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    # Create reproducible builds
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.commitDate={{ .CommitDate }}
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath

nfpms:
  - maintainer: Siemens AG <coaty.team@gmail.com>
    description: Data Distribution Agent
    homepage: https://github.com/coatyio/dda
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - dda.yaml
      - apis/grpc/protos/*
      - src: apis/grpc/stubs/js/*
        dst: apis/grpc-web/stubs/js

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ .Version }}-next"

changelog:
  sort: asc
  filters:
    include:
      - '^.*?feat(\([[:word:]]+\))??!?:'
      - '^.*?fix(\([[:word:]]+\))??!?:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

dockers:
  - image_templates:
      - "ghcr.io/coatyio/{{ .ProjectName }}:{{ .Version }}"
      - "ghcr.io/coatyio/{{ .ProjectName }}:latest"
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description=Data Distribution Agent
      - --label=org.opencontainers.image.url=https://github.com/coatyio/dda
      - --label=org.opencontainers.image.source=https://github.com/coatyio/dda
      - --label=org.opencontainers.image.documentation=https://coatyio.github.io/dda
      - --label=org.opencontainers.image.licenses=MIT
      - --label=org.opencontainers.image.vendor=Siemens AG
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
