/**
 * @fileoverview gRPC-Web generated client stub for dda.state.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.3
// source: state.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.dda = {};
proto.dda.state = {};
proto.dda.state.v1 = require('./state_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dda.state.v1.StateServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.dda.state.v1.StateServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dda.state.v1.Input,
 *   !proto.dda.state.v1.Ack>}
 */
const methodDescriptor_StateService_ProposeInput = new grpc.web.MethodDescriptor(
  '/dda.state.v1.StateService/ProposeInput',
  grpc.web.MethodType.UNARY,
  proto.dda.state.v1.Input,
  proto.dda.state.v1.Ack,
  /**
   * @param {!proto.dda.state.v1.Input} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dda.state.v1.Ack.deserializeBinary
);


/**
 * @param {!proto.dda.state.v1.Input} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.dda.state.v1.Ack)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.dda.state.v1.Ack>|undefined}
 *     The XHR Node Readable Stream
 */
proto.dda.state.v1.StateServiceClient.prototype.proposeInput =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/dda.state.v1.StateService/ProposeInput',
      request,
      metadata || {},
      methodDescriptor_StateService_ProposeInput,
      callback);
};


/**
 * @param {!proto.dda.state.v1.Input} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.dda.state.v1.Ack>}
 *     Promise that resolves to the response
 */
proto.dda.state.v1.StateServicePromiseClient.prototype.proposeInput =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/dda.state.v1.StateService/ProposeInput',
      request,
      metadata || {},
      methodDescriptor_StateService_ProposeInput);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dda.state.v1.ObserveStateChangeParams,
 *   !proto.dda.state.v1.Input>}
 */
const methodDescriptor_StateService_ObserveStateChange = new grpc.web.MethodDescriptor(
  '/dda.state.v1.StateService/ObserveStateChange',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.dda.state.v1.ObserveStateChangeParams,
  proto.dda.state.v1.Input,
  /**
   * @param {!proto.dda.state.v1.ObserveStateChangeParams} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dda.state.v1.Input.deserializeBinary
);


/**
 * @param {!proto.dda.state.v1.ObserveStateChangeParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dda.state.v1.Input>}
 *     The XHR Node Readable Stream
 */
proto.dda.state.v1.StateServiceClient.prototype.observeStateChange =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dda.state.v1.StateService/ObserveStateChange',
      request,
      metadata || {},
      methodDescriptor_StateService_ObserveStateChange);
};


/**
 * @param {!proto.dda.state.v1.ObserveStateChangeParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dda.state.v1.Input>}
 *     The XHR Node Readable Stream
 */
proto.dda.state.v1.StateServicePromiseClient.prototype.observeStateChange =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dda.state.v1.StateService/ObserveStateChange',
      request,
      metadata || {},
      methodDescriptor_StateService_ObserveStateChange);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.dda.state.v1.ObserveMembershipChangeParams,
 *   !proto.dda.state.v1.MembershipChange>}
 */
const methodDescriptor_StateService_ObserveMembershipChange = new grpc.web.MethodDescriptor(
  '/dda.state.v1.StateService/ObserveMembershipChange',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.dda.state.v1.ObserveMembershipChangeParams,
  proto.dda.state.v1.MembershipChange,
  /**
   * @param {!proto.dda.state.v1.ObserveMembershipChangeParams} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.dda.state.v1.MembershipChange.deserializeBinary
);


/**
 * @param {!proto.dda.state.v1.ObserveMembershipChangeParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dda.state.v1.MembershipChange>}
 *     The XHR Node Readable Stream
 */
proto.dda.state.v1.StateServiceClient.prototype.observeMembershipChange =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dda.state.v1.StateService/ObserveMembershipChange',
      request,
      metadata || {},
      methodDescriptor_StateService_ObserveMembershipChange);
};


/**
 * @param {!proto.dda.state.v1.ObserveMembershipChangeParams} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.dda.state.v1.MembershipChange>}
 *     The XHR Node Readable Stream
 */
proto.dda.state.v1.StateServicePromiseClient.prototype.observeMembershipChange =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/dda.state.v1.StateService/ObserveMembershipChange',
      request,
      metadata || {},
      methodDescriptor_StateService_ObserveMembershipChange);
};


module.exports = proto.dda.state.v1;

